version: '3.4'

services:
  nationalactsweb:
    image: nationalactsusers
    container_name: nationalactsusers
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - app-network
    ports:
      - 3000:3000    

networks:
  app-network:
    driver: bridge
    
volumes:
  db_data: