import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useCurrentUser } from "../src/hooks/useCurrentUser";
import { useLogout } from "../src/hooks/useLogout";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { user: currentUser } = useCurrentUser();
  const { logout } = useLogout();
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>National Acts User Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          User main landing page
        </h1>

        <p className={styles.description}>
          {currentUser
            ? `Hello ${currentUser.username} `
            : "You are not logged in !"}
          <br />
          {currentUser
            ? <button
                onClick={() => {
                  logout();
                  router.push("/login");
                }}
                className="mt-2 border border-solid border-black py-2 px-4 rounded cursor-pointer"
              >
            Logout
          </button>
            : ''
          }
        </p>

      </main>

      <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </footer>
    </div>
  );
}
